### ISSUE TITLE
Add support for 3D viewer

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-powerbi#13]
From forum: https://speckle.community/t/3d-models-visuals-in-power-bi/1429/12

**Comment by andrewringler** [comment]
Hi. We created a Power BI Visual (plugin) that pulls data directly from Speckle and views it in Power BI. https://github.com/specklesystems/speckle-powerbi , it currently only works with Speckle V1, but I think it could be migrated to V2. It currently, is 2D-ish, since it was focused on viewing floorplans, and we wanted nice support for Power BI export to SVG, but the actual viewer is ThreeJS (copied from the Speckle V1 Vue App), so it shouldn't be too much work to make it support 3D, I think. I am seeing if I can create a team to work on this during the upcoming Speckle Hackathon (although since it isn't a new project it wouldn't be able to compete for prizes). https://speckle.community/t/hackathon-into-the-speckleverse/2494/7

**Comment by teocomi** [comment]
Nice, keep us posted and let us know how we can help!

**Comment by benjamincaspersmith** [comment]
Definitely would be interested in an update on this!

**Comment by andrewringler** [comment]
I just published the git repo, in its current state. So still a 2D-ish experience with Speckle V1 only, but I will keep you posted.

https://github.com/Payette/speckle-powerbi-visual

**Comment by AlanRynne** [comment]
Closing this as we've added an `alpha` version of our 3D viewer for PowerBI.

It can be found at https://github.com/specklesystems/speckle-powerbi-visuals
